server:
  port: 8085

spring:
  application:
    name: LICENSE-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296
  # Database Connection
  datasource:
    driver-class-name: org.postgresql.Driver    
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cis_license_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWD:postgres}
    # HikariCP Configuration	  
    hikari:
      minimumIdle: 0
      maximum-pool-size: 40
      maxLifetime: 900000
      transaction-isolation: TRANSACTION_READ_COMMITTED
      auto-commit: false
      data-source-properties:
        useServerPrepStmts: false
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 1024
  # JPA Properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true    
    # Hibernate properties
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time-zone: UTC
          batch-size: 15
        order-inserts: true
        order-updates: true
        connection:
          provider-disables-autocommit: true
        query:
          in-clause-parameter-padding: true
          fail-on-pagination-over-collection-fetch: true
          plan-cache-max-size: 4096
  # SQL Properties
  sql:
    init:
      mode: always
      platform: postgres

# Circiut Breaker      
resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - "*"
  tracing:
    sampling:
      probability: 1.0        